title: Sakin Güzel Kız
author: ramazantufekci
email: saun@icin.bos
description: > # this means to ignore newlines until "baseurl:"
  Google de arandığı zaman bu yazı çıkacaksa kesinlikle buraya birşeyler yazmalıyım.

# social links
twitter_username: your-twitter-handle
github_username:  ramazantufekci

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
